EMAIL_SUBJECT = 'Your Usage Report'
EMAIL_BODY = 'Attached is your usage CSV report'
CSV_FILE_NAME = 'usage_logs.csv'
EMAIL_SENT_SUCCESS = 'CSV sent to your email successfully'
EMAIL_SENT_FAIL = 'Failed to send email'
FAILED_TO_FETCH = 'Failed to fetch data.'
REVENUE_RETRIEVED_SUCCESS = "Revenue retrieved successfully"
MONTHLY_USAGE_RETRIEVED_SUCCESS = "Monthly usage retrieved successfully"
MODEL_USAGE_RETRIEVED_SUCCESS = "Usage by model retrieved successfully"
TOP_USER_RETRIEVED_SUCCESS = "Top user retrieved successfully"
TOP_MODEL_RETRIEVED_SUCCESS = "Top models retrieved successfully"