# Generated by Django 5.2.12 on 2026-04-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='aiproduct',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
